#!/bin/sh -u

# get the current OpenBSD snapshot

REL=39				# "37" for OpenBSD 3.7, etc.
RELEASEDIR=`echo $REL | sed -e 's/./&./'`	# e.g., "3.7" etc.
SNAPDIR="snapshots"

EXT=.tgz
PATT='*'					# what go get

SITE=ftp1.ca.openbsd.org	# where to get it from
FROMDIR=pub/OpenBSD

TODIR=OpenBSD				# where to put it

ARCH=`uname -m`

PROTO=ftp			# how to get it, other options http scp 
VERBOSE=""			# how chattily to get it

# Where to put it
if [ -d ~/download ]; then
	BASEDIR=~/download/${TODIR}
elif [ -d ~ftp/pub ]; then
	BASEDIR=~ftp/pub/${TODIR}		# where to put it locally
else
	echo "No download directory found" >&2
	exit 1
fi

USAGE="$0 [-s][-a arch ][-b local-Basedir][ -f host] [-p patt]
-a arch := i386|sparc|hppa|...
-h use http 
"

function usage {		# give usage message, and exit
	echo "Usage: $USAGE" 2>&1
	exit 1
}

while getopts "a:b:f:hp:s" opt 
do 
 	 case "$opt" in 
		a)	ARCH=$OPTARG ;;
		b)	BASEDIR=$OPTARG ;;
		f)	
			case "$OPTARG" in
			dos) SITE=ftp.darwinsys.com;;
			ob|sunsite) SITE=ftp.openbsd.org;;
			rtfm) SITE=rt.fm;;
			*)		SITE=${OPTARG};;
			esac
			;;
		h)	PROTO=http;;
		p)	PATT=${OPTARG};;
		s)	SNAPDIR="${RELEASEDIR}"
			echo "****************************************************"
			echo "$0: -s means to NOT use snapshot, using ${RELEASEDIR}"
			echo "****************************************************"
			echo -n "OK? "; read answer
			;;
		v)	VERBOSE=v;;
		*)	usage;;
	esac
done
shift `expr $OPTIND - 1`		 # leave just filenames

# Where to download it to
DIR=${BASEDIR}/${SNAPDIR}/${ARCH}
if [ ! -d ${DIR} ]; then
	mkdir -p ${DIR}
fi
cd ${DIR} || exit


if [ $# -ne 0 ]; then
	usage
fi

case ${PROTO} in
ftp)
	set -x
	ftp -a ftp://${SITE}/${FROMDIR}/${SNAPDIR}/${ARCH}/${PATT}
	;;
http)
	set -x
	ftp -a http://${SITE}/${FROMDIR}/${SNAPDIR}/${ARCH}/${PATT}
	;;
ssh)
	set -x
	scp -r ian@${SITE}:~ftp/${PREFIX}/${TOP}/${ARCH}/${PATT} .
	;;
esac
