#!/bin/sh

# obaudit - check the state of an OpenBSD system

uname -a

if [ -f /usr/src/Makefile ]; then
	echo 'Some /usr/src present: \'
	ls -l /usr/src
else
	echo "No /usr/src"
fi
if [ -f /etc/pf.conf ]; then
	echo "pf.conf found:\c"
	ls -l /etc/pf.conf
fi
if [ -f /etc/ipf.conf ]; then
	echo '** Warning: ipf.conf found **\c'
	if [ -f /etc/pf.conf ]; then
		echo '(AND pf.conf too; needs cleanup?) **'
	else
		echo '(but NO pf.conf; may need to rename it) **'
	fi
else
	echo "No ipf.conf"
fi
if [ -f /etc/nat.conf ]; then
	echo '** Warning: nat.conf found, may need to merge into pf.conf **'
else
	echo "No nat.conf"
fi

# create entries in this format in the passwd and group files.
# _tftpd:*:79:79::0:0:TFTP daemon:/var/empty:/sbin/nologin
# _portmap:*:28:
while read pw_nam pw_uid pw_gecos
do
	grep "^$pw_nam" /etc/passwd >/dev/null && continue
	echo "Missing $pw_nam, adding it..."
	# cannot use -g =uid as it was only added in 3.4 or 3.5
	sudo ksh -c "echo ${pw_nam}:*:${pw_uid}: >> /etc/group"
	sudo useradd -c "${pw_gecos}" -d /var/empty	\
            -u ${pw_uid} -g ${pw_uid} \
            -s /sbin/nologin ${pw_nam}
	# OpenBSD's useradd will create the group automatically.
done <<!
_portmap 28 portmap
_identd 29 identd
_rstatd 30 rpc.rstatd
_rusersd 32 rpc.rusersd
_fingerd 33 fingerd
_x11 35 X server
_isakmpd 68 isakmpd privsep
_syslogd 73 Syslog Daemon
_pflogd 74 pflogd privsep
_bgpd 75 BGP Daemon
_tcpdump 76 tcpdump
_dhcp 77 dhcp programs
_mopd 78 MOP daemon
_tftpd 79 TFTP daemon
_rbootd 80 rbootd Daemon
_afs 81 afs daemon
_ppp 82 PPP utilities
_ntp 83 NTP Daemon
_ftp 84 FTP Daemon
_ospfd 85 OSPF Daemon
_hostapd 86 HostAP Daemon
_dvmrpd 87 DVMRP Daemon
_ripd   88 RIP Daemon
_relayd 89 Relay Daemon
_ospf6d 90 OSPF6 Daemon
_snmpd 91 91 SNMP Daemon
_rtadvd 92 92 IPv6 Router Advertisement Daemon
_ypldap 93 93 YP to LDAP Daemon
_btd 94 94 Bluetooth Daemon
_smtpd 95 95 SMTP Daemon
_rwalld 96 96 rwall Daemon
_nsd 97 97 NSD Daemon
_ldpd 98 98 LDPD Daemon
_sndio 98 98 sndio privsep
!
grep '^_hoststated:' /etc/passwd && echo "Warning: must remove hoststated user"
