#!/bin/sh

# Set up a machine for minimally testing suspend/resume.

# Set this to the UUID of the disk your /tmp resides on, if you want it newfs'd
TMP_UUID=103d1286e8b0290c
# set this to the partition of your /tmp; will get newfs'd(~) on reboot
TMP_PART=d
set -x
fsck -p /
mount   /
fsck -p /usr
mount   /usr
fsck -p /var
mount   /var
grep "${TMP_UUID}.${TMP_PART} /tmp" /etc/fstab && newfs ${TMP_UUID}.${TMP_PART}
fsck -p /tmp
mount /tmp
chmod 01777 /tmp
apmd -C
export TERM=vt220
set +x

echo "Now you can try suspending or hibernating..."
