#!/bin/sh
set -x
fsck -p /
mount   /
fsck -p /usr
mount   /usr
fsck -p /var
mount   /var
grep '103d1286e8b0290c.d /tmp' /etc/fstab && newfs 103d1286e8b0290c.d
mount /tmp
chmod 01777 /tmp
apmd -C
export TERM=vt220
set +x
