#!/bin/sh

# quickupdate -- quickly update base files from snapshot

REL=27				# "26" for OpenBSD 2.6, etc.
case ${REL} in
	2[0-6])		EXT=tar.gz;;
	2[789]|3*)	EXT=tgz;;
esac

#ARCH=sparc
ARCH=i386

cd /usr/download/OpenBSD/${ARCH} || exit

DEST=/
#DEST=/export/dartboard/root

# NEVER include etc in this list, or you will die horribly!
BDIRS="base comp misc man"
XDIRS="xbase xfont xserv xshare"

#DIRS="${BDIRS}"
#DIRS="${BDIRS} ${XDIRS}"
DIRS="${XDIRS}"

for f in ${DIRS}
do
	echo ===== START $f
	(cd ${DEST} || exit; sudo tar xvzpf - ) < ${f}${REL}.${EXT}
done

if [ -f bsd ]; then
	cp bsd ${DEST}/nbsd

	cd ${DEST}
	if [ -f bsd -a -f nbsd ]; then
		mv bsd obsd
		mv nbsd bsd
	fi
fi
