#!/bin/sh

# quickupdate -- quickly update base files from snapshot

REL=29				# "26" for OpenBSD 2.6, etc.
RELDIR=2.9			# same but with a dot
RELDIR=snapshots	# when not -stable
case ${REL} in
	2[0-6])		EXT=tar.gz;;
	2[789]|3*)	EXT=tgz;;
esac

#ARCH=sparc
ARCH=i386

if [ -d /usr/download/OpenBSD/${RELDIR}/${ARCH} ]; then
	 cd /usr/download/OpenBSD/${RELDIR}/${ARCH} || exit
elif [ -d ~ftp/pub/OpenBSD/${RELDIR}/${ARCH} ]; then
	 cd ~ftp/pub/OpenBSD/${RELDIR}/${ARCH} || exit
fi

DEST=/
#DEST=/export/dartboard/root

# NEVER include etc in this list, or you will die horribly!
BDIRS="base comp misc man"
XDIRS="xbase xfont xserv xshare"

#DIRS="${BDIRS}"
DIRS="${BDIRS} ${XDIRS}"
#DIRS="${XDIRS}"

for f in ${DIRS}
do
	FILE="${f}${REL}.${EXT}"
	if [ -f ${FILE} ]; then
		echo "===> $f (${FILE})" >&2
	else
		echo "Cannot locate file ${FILE}"
		exit
	fi
	(cd ${DEST} || exit; sudo tar xvzpf - ) < ${FILE}
done

if [ -f bsd ]; then
	sudo cp bsd ${DEST}/nbsd && echo Kernel installed as /nbsd
fi

echo "*** REMEMBER TO RUN POSTUPGRADE ***"
