#!/bin/sh

# quickupdate -- quickly update base files from snapshot

#ARCH=sparc
ARCH=i386

cd /usr/download/OpenBSD/${ARCH} || exit

DEST=/
#DEST=/export/dartboard/root

# NEVER include etc in this list, or you will die horribly!
BDIRS="base comp misc man"
XDIRS="xbase xfont xserv xshare"

#DIRS="${BDIRS}"
DIRS="${BDIRS} ${XDIRS}"
#DIRS="${XDIRS}"

for f in ${DIRS}
do
	echo ===== START $f
	(cd ${DEST} || exit; sudo tar xvzpf - ) < ${f}26.tar.gz
done

cp bsd ${DEST}/nbsd

cd ${DEST}
if [ -f bsd -a -f nbsd ]; then
	mv bsd obsd
	mv nbsd bsd
fi
