.Dd $Mdocdate$
.Dt OBAUDIT 8
.Os
.Sh NAME
.Nm obaudit 
.Nd update some files on your OpenBSD system and check for a few update anomalies
.Sh SYNOPSIS
.Nm obaudit
.Sh DESCRIPTION
The
.Nm
program updates some files on your OpenBSD system and checks for a few update anomalies
.Sh AUTHORS
Ian Darwin
.Sh CAVEATS
This program is misnamed: it is not a real auditing tool.
