.Dd $Mdocdate$
.Dt OBAUDIT 8
.Os
.Sh NAME
.Nm obaudit 
.Nd update some files on your OpenBSD system and check for a few update anomalies
.Sh SYNOPSIS
.Nm obaudit
.Sh DESCRIPTION
The
.Nm
program updates some files on your OpenBSD system and checks for a few update anomalies
.Pp
Note that in the process, it will blindly remove files that are no
longer in base, whether you have edited them or not!
.Sh AUTHORS
Ian Darwin
.Sh CAVEATS
This program is misnamed: it is not a real auditing tool.
