#!/bin/sh

# Set up a machine for minimally testing suspend/resume.

# Set this to the UUID of the disk your /tmp resides on, if you want it newfs'd
# WARNING: omitting this is not supported yet, so no "if you want it" yet
TMP_UUID=239b56351e4575ef
# set this to the partition of your /tmp; will get newfs'd(~) on reboot
TMP_PART=d
# set this to the minimal list of FSes you need
REST="/var /usr /usr/X11R6"

set -x
fsck -p /
mount   /

if [ ${TMP_UUID} != "" ]; then
	grep "${TMP_UUID}.${TMP_PART} /tmp" /etc/fstab && newfs ${TMP_UUID}.${TMP_PART}
	fsck -p /tmp
	mount /tmp
	chmod 01777 /tmp
fi

for fs in ${REST}; do
	fsck -p ${fs}
	mount   ${fs}
done

apmd -C
export TERM=vt220
set +x

echo "Now you can try one of the things..."
